build:
  image: python:$$PYTHON_VERSION
  commands:
    - pip install -r requirements.txt
    - python setup.py install
    - flake8 setup.py drone tests
    - nosetests -v --with-coverage--cover-package jin2cli 

matrix:
  PYTHON_VERSION:
    - 2.7
    - 3.4
    - 3.5
