build:
  image: python:$$PYTHON_VERSION
  commands:
    - pip install -r test_requirements.txt
    - python setup.py install
    - nosetests -v --with-coverage--cover-package jin2cli 


matrix:
  PYTHON_VERSION:
    - 2.7
    - 3.4
    - 3.5
