language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
install:
  - "pip install -r test_requirements.txt"
  - "python setup.py install"
script: "nosetests -v --with-coverage --cover-package=jin2cli"
